### PR TITLE
Improved CyberNvim

### PR DESCRIPTION
**Pull request by olivertzeng**
various improvements in this commit including
formatted the lua files
added submodule for new users
removed deprecated plugins software like bashtop to btop, and api functions
and alphabetically ordered a lot of stuff

### CODE REVIEW

**Comment by pgosar** [comment]
Thanks for the PR

Don't remove the example config, that's pretty important. I'll take a look at the rest later

**Comment by olivertzeng** [comment]
Well the example config is already in the lua/user directory
 Sent from Proton Mail for iOS 
於 週五, 4月 19, 2024 時間 00:02, Pranay Gosar ***@***.***&gt; 寫道：  Thanks for the PR
Don't remove the example config, that's pretty important. I'll take a look at the rest later

**Comment by olivertzeng** [comment]
But it’s not named example config
 Sent from Proton Mail for iOS 
於 週五, 4月 19, 2024 時間 00:02, Pranay Gosar ***@***.***&gt; 寫道：  Thanks for the PR
Don't remove the example config, that's pretty important. I'll take a look at the rest later

**Comment by pgosar** [comment]
the one in user is the personal config. example is separate

**Comment by olivertzeng** [comment]
Oh really? Good to know because I thought that it is just the same file as user/user_config.luaI’ll revert the changesYou can check out my main branch to see how I have managed to have a proper nvim config without that fileNormally I wouldn’t like that because of the file nameYou prob should call it settings.lua and have a comment say that it’s an example fileShould I do the latter or the formerMessage ID: ***@***.***&gt;

**Comment by pgosar** [comment]
I think example_user_config is pretty clear, let's keep it as it was for now

**Comment by pgosar** [comment]
I also immediately get errors. I would avoid getting rid of some of those setup calls. Be sure to test everything
image

**Comment by olivertzeng** [comment]
> I also immediately get errors. I would avoid getting rid of some of those setup calls. Be sure to test everything
> 
> image
> 
> 

Whoops I'll try it later when I'm free

**Comment by olivertzeng** [comment]
> I also immediately get errors. I would avoid getting rid of some of those setup calls. Be sure to test everything image

Alright fixed

try again

**Comment by olivertzeng** [comment]
@pgosar i've also make some plugins to always fetch the latest including trouble and neo-tree

and also installed [better-escape.nvim](https://github.com/max397574/better-escape.nvim) as well, you can press `jj` or set it in the config to escape from insert mode

**Comment by pgosar** [comment]
I would say that the plugin you added is better suited for your personal configuration. Please make sure not to remove the example user configuration, along with the code in plugins that supports disabling plugins. Out of this PR I am mainly interested in the cleanup you have done to the main-options and some of the style changes in various other files.

**Comment by olivertzeng** [comment]
> I would say that the plugin you added is better suited for your personal configuration. Please make sure not to remove the example user configuration, along with the code in plugins that supports disabling plugins. Out of this PR I am mainly interested in the cleanup you have done to the main-options and some of the style changes in various other files.

after some time i've figured out that CyberNvim isn't something like kickstart
it's something like lazyvim
sorry for that

but tbh i think that since there is about 2k loc it is better to just make the whole codebase itself a neovim config rather than seperating them

**Pull request closed without merging**
